label encoded geography

Data Preporcessing

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv(r"C:\Users\okechukwu chude\Documents\Neural Network\Customer Churn\Churn_Modelling.csv")
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [3]:
print(dataset.head())

   RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         790

Encoding categorical data


In [4]:
# Label Encoding the "geography" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 1] = le.fit_transform(x[:, 1])
print(x)

[[619 0 'Female' ... 1 1 101348.88]
 [608 2 'Female' ... 0 1 112542.58]
 [502 0 'Female' ... 1 0 113931.57]
 ...
 [709 0 'Female' ... 0 1 42085.58]
 [772 1 'Male' ... 1 0 92888.52]
 [792 0 'Female' ... 1 0 38190.78]]


In [5]:
# Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])
print(x)

[[619 0 0 ... 1 1 101348.88]
 [608 2 0 ... 0 1 112542.58]
 [502 0 0 ... 1 0 113931.57]
 ...
 [709 0 0 ... 0 1 42085.58]
 [772 1 1 ... 1 0 92888.52]
 [792 0 0 ... 1 0 38190.78]]


In [6]:
# Get the first two rows
first_two_rows = x[:2]

print(first_two_rows)

[[619 0 0 42 2 0.0 1 1 1 101348.88]
 [608 2 0 41 1 83807.86 1 0 1 112542.58]]


Splitting into training and test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Developing the ANN

In [9]:
#importing keras libraries and packges
import keras
from keras.models import Sequential #required to initialise ann
from keras.layers import Dense # required to build laters of ann

Initialising the ANN

In [10]:
classifier = Sequential()

Adding the input layer and the first hidden layer

In [11]:
classifier.add(Dense(units=6, activation='relu', input_dim=10))

Adding the second hidden layer

In [12]:
classifier.add(Dense(units=6, activation='relu'))

Adding the output layer

In [13]:
classifier.add(Dense(units=1, activation='sigmoid'))

Compiling the ANN

In [14]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])

Fitting the ANN to training set

In [15]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
800/800 [==============================] - 3s 2ms/step - loss: 0.4996 - accuracy: 0.7947
Epoch 2/100
800/800 [==============================] - 2s 2ms/step - loss: 0.4355 - accuracy: 0.8076
Epoch 3/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4187 - accuracy: 0.8192
Epoch 4/100
800/800 [==============================] - 1s 2ms/step - loss: 0.4053 - accuracy: 0.8316
Epoch 5/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3927 - accuracy: 0.8388
Epoch 6/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3816 - accuracy: 0.8440
Epoch 7/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3721 - accuracy: 0.8478
Epoch 8/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3658 - accuracy: 0.8487
Epoch 9/100
800/800 [==============================] - 1s 2ms/step - loss: 0.3613 - accuracy: 0.8514
Epoch 10/100
800/800 [==============================] - 2s 2ms/step - loss: 0.3585 - accura